# Render.com deployment configuration for Rio Terminal
#
# Credits: Based on Rio Terminal by Raphael Amorim
# Original project: https://github.com/raphamorim/rio
# Author: Raphael Amorim <rapha850@gmail.com>
# License: MIT
#
services:
  - type: web
    name: rio-terminal-docker
    env: docker
    repo: https://github.com/jeorgiba/rio-terminal.git
    branch: main
    dockerfilePath: ./Dockerfile.demo
    plan: free
